### ISSUE TITLE
gradlew build fails on win10

### ISSUE THREAD

**Issue by MartinEngen** [enonic/starter-babel#3]
I seem to encounter 2 issues with this starter.

Running it straight out of the box, I get the message:

```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':npmInstall'.
 A problem occurred starting process 'command 'C:\Users\Martin\Documents\Development\Enonic\sourcecode\reacting\.gradle\nodejs\node-v4.2.1-win-x64\node.exe''

```

It seems like the node version 4.2.1 does not install correctly.
Updating to the newest version 9.4.0 fixes this..

But this leads on to another error:
```
> Task :babelJs
C:\Users\Martin\Documents\Development\Enonic\sourcecode\reacting\node_modules\.bin\babel:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':babelJs'.
> Process 'command 'C:\Users\Martin\Documents\Development\Enonic\sourcecode\reacting\.gradle\nodejs\node-v9.4.0-win-x64\node.exe'' finished with non-zero exit value 1
```
Is this windows specific? Any idea how to get around this?

**Comment by tommyy** [comment]
@MartinEngen Did you get this to work? I'm struggling with the same issue.

**Comment by MartinEngen** [comment]
@tommyy No, I was not able to get this working after all. I did make a thread on the forum without much luck as well https://discuss.enonic.com/t/starter-babel-will-not-build-on-win10/1394/2

You could mention that you got a problem as well, so that it might get more attention

**Comment by alansemenov** [comment]
@tommyy @MartinEngen we're looking into this.

**Comment by alansemenov** [comment]
@tommyy @MartinEngen can you get the latest and check if it builds for you? if there are no issues we'll release the new version.
